# Generated by Django 5.2.3 on 2025-06-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_habits', to='routines.routine')),
            ],
        ),
    ]
