# Generated by Django 5.2.3 on 2025-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledroutine',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledroutine',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
