# Generated by Django 5.2.3 on 2025-07-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduledroutine_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledroutine',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
