# Generated by Django 5.2.3 on 2025-07-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduledroutine_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledroutine',
            name='scheduled_time',
        ),
    ]
