# Generated by Django 5.2.3 on 2025-07-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_scheduledroutine_scheduled_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledroutine',
            options={'verbose_name_plural': 'Scheduled Routines'},
        ),
    ]
