# Generated by Django 5.2.3 on 2025-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_scheduledroutine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledroutine',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledroutine',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
