# Generated by Django 5.1.6 on 2025-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_scheduledroutine_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledroutine',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
