# Generated by Django 5.1.6 on 2025-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_scheduledroutine_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledroutine',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
