# Generated by Django 5.2.3 on 2025-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('', ''), ('Physical', 'Physical'), ('Mental', 'Mental'), ('Creative', 'Creative'), ('Financial', 'Financial')], default='', max_length=35, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_habits_per_day', models.IntegerField(default=1)),
            ],
        ),
    ]
