# Generated by Django 5.2.3 on 2025-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Mental', 'Mental'), ('Creative', 'Creative'), ('Financial', 'Financial')], default='Physical', max_length=35),
            preserve_default=False,
        ),
    ]
