# Generated by Django 5.2.3 on 2025-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('', 'Select a category type'), ('Physical', 'Physical'), ('Mental', 'Mental'), ('Creative', 'Creative'), ('Financial', 'Financial')], default='', max_length=35, unique=True),
        ),
    ]
