# Generated by Django 5.2.3 on 2025-06-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_category_name_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('', 'Default'), ('Physical', 'Physical'), ('Mental', 'Mental'), ('Creative', 'Creative'), ('Financial', 'Financial')], default='', max_length=35),
        ),
    ]
