# Generated by Django 5.2.3 on 2025-07-10 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('', 'Select a category type'), ('Physical', 'Physical'), ('Mental', 'Mental'), ('Creative', 'Creative'), ('Financial', 'Financial')], default='', max_length=35),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'category_type'), name='unique_category_type_per_user'),
        ),
    ]
