# Generated by Django 5.2.3 on 2025-06-15 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(default='example name', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='The routine name must be at least 3 characters long.')]),
            preserve_default=False,
        ),
    ]
