services:
  - type: web
    name: solidify
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "bash build.sh"
    startCommand: "gunicorn SOLIDIFY.wsgi:application"
    healthCheckPath: /accounts/login/
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: "False"
      - key: DB_SSLMODE
        value: require
      - key: DB_PORT
        value: "5432"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
