# Generated by Django 5.2.3 on 2025-06-17 09:33

import SOLIDIFY.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', SOLIDIFY.accounts.managers.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
