# Generated by Django 5.2.3 on 2025-06-24 05:27

import SOLIDIFY.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_options_alter_appuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[SOLIDIFY.accounts.validators.NameValidator('First name')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[SOLIDIFY.accounts.validators.NameValidator('Last name')]),
        ),
    ]
