# Generated by Django 5.2.3 on 2025-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='dopamine_type',
            field=models.CharField(choices=[('', 'Select a category type'), ('Anticipatory', 'Anticipatory'), ('Reward', 'Reward'), ('Both', 'Both')], default='', max_length=35),
        ),
    ]
