# Generated by Django 5.2.3 on 2025-06-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(default='example', max_length=30),
            preserve_default=False,
        ),
    ]
