# Generated by Django 5.2.3 on 2025-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_dopamine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='dopamine_type',
            field=models.CharField(choices=[('', 'Select dopamine type'), ('Anticipatory', 'Anticipatory'), ('Reward', 'Reward'), ('Both', 'Both')], default='', max_length=35),
        ),
    ]
