# Generated by Django 5.2.3 on 2025-07-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_dopamine_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name_plural': 'Habits'},
        ),
    ]
