# Generated by Django 5.2.3 on 2025-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
