# Generated by Django 5.2.3 on 2025-07-10 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_category_type_and_more'),
        ('habits', '0005_alter_habit_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('user', 'habit_name'), name='unique_habit_per_user'),
        ),
    ]
