# Generated by Django 5.2.3 on 2025-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Sports', 'Sports'), ('Family and Free Time', 'Family and Free Time'), ('Physical and Mental Health', 'Physical and Mental Health'), ('Financial Wealth', 'Financial Wealth'), ('Balance between All', 'Balance between All')], max_length=35)),
            ],
        ),
    ]
