# Generated by Django 5.2.3 on 2025-06-16 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='The routine name must be at least 3 characters long.')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_routines', to='categories.category')),
                ('recommended_habits', models.ManyToManyField(blank=True, related_name='recommended_in_routines', to='habits.habit')),
            ],
        ),
    ]
