# Generated by Django 5.2.3 on 2025-07-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'verbose_name_plural': 'Routines'},
        ),
    ]
