# Generated by Django 5.2.3 on 2025-06-24 08:38

import SOLIDIFY.routines.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_created_at'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='recommended_habits',
        ),
        migrations.AddField(
            model_name='routine',
            name='habits',
            field=models.ManyToManyField(blank=True, related_name='habits_routines', to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='The routine name must be at least 3 characters long.'), SOLIDIFY.routines.validators.RoutineNameValidator()]),
        ),
    ]
