# Generated by Django 5.2.3 on 2025-07-10 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_category_type_and_more'),
        ('habits', '0006_habit_unique_habit_per_user'),
        ('routines', '0002_alter_routine_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('user', 'routine_name'), name='unique_routine_per_user'),
        ),
    ]
